# project definitions
project: addinx_howto
audience: everyone
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/addinx/everyone
topnav_title: Add-in X Documentation
homepage_title: Add-in X Documentation
site_title: Add-in X
project_folder: addinx
company_name: Addin X
footer_image_location: ../common_images/125-addinX-logo.png
sidebar_image_location: ../common_images/company_logo.png
github_editme_path:
disqus_shortname: 
# variables


sidebar_tagline: Add-in X
sidebar_version: Documentation 1.0
theme_file: theme-green.css
pdf_file_name: addinx_howto_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/addinx_everyone*

# same for all
host: 127.0.0.1


highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

